package stores

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestNewStackStore(t *testing.T) {
	tmpDir := t.TempDir()

	// Create stacks directory and a stack file
	stacksDir := filepath.Join(tmpDir, "stacks")
	os.MkdirAll(stacksDir, 0755)

	stackContent := `version: v0
stack:
  description: "Test stack"
  env:
    TZ: Europe/Paris
    TEST_NETWORK: testnet
  layers:
    - layer: layers/1.services
      plan: my-service
      env:
        PORT: "8080"
    - layer: layers/2.proxy
      plan: my-proxy
`
	os.WriteFile(filepath.Join(stacksDir, "test.yaml"), []byte(stackContent), 0644)

	store, err := NewStackStore(tmpDir, "test", false)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if store.Name != "test" {
		t.Fatalf("expected name 'test', got '%s'", store.Name)
	}
	if store.Definition.Stack.Description != "Test stack" {
		t.Fatalf("expected description 'Test stack', got '%s'", store.Definition.Stack.Description)
	}
	if len(store.Definition.Stack.Layers) != 2 {
		t.Fatalf("expected 2 layers, got %d", len(store.Definition.Stack.Layers))
	}
	if store.Definition.Stack.Layers[0].Plan != "my-service" {
		t.Fatalf("expected plan 'my-service', got '%s'", store.Definition.Stack.Layers[0].Plan)
	}
	if store.Definition.Stack.Layers[0].Env["PORT"] != "8080" {
		t.Fatalf("expected PORT=8080, got '%s'", store.Definition.Stack.Layers[0].Env["PORT"])
	}
}

func TestNewStackStore_NotFound(t *testing.T) {
	tmpDir := t.TempDir()
	os.MkdirAll(filepath.Join(tmpDir, "stacks"), 0755)

	_, err := NewStackStore(tmpDir, "nonexistent", false)
	if err == nil {
		t.Fatal("expected error for nonexistent stack")
	}
}

func TestLayerDetectType_Shell(t *testing.T) {
	tmpDir := t.TempDir()
	verbsDir := filepath.Join(tmpDir, "verbs")
	os.MkdirAll(verbsDir, 0755)
	os.WriteFile(filepath.Join(verbsDir, "up.sh"), []byte("echo up"), 0644)

	rt := layerDetectType(tmpDir)
	if rt != recipeShell {
		t.Fatalf("expected shell, got %s", rt)
	}
}

func TestLayerDetectType_Unknown(t *testing.T) {
	tmpDir := t.TempDir()
	rt := layerDetectType(tmpDir)
	if rt != recipeUnknown {
		t.Fatalf("expected unknown, got %s", rt)
	}
}

func TestLayerRef(t *testing.T) {
	ref := layerRef("layers/2.locals-subscriptions", "ollama-registry")
	if ref != "2.locals-subscriptions/ollama-registry" {
		t.Fatalf("unexpected ref: %s", ref)
	}
}

func TestLayerListVerbs(t *testing.T) {
	tmpDir := t.TempDir()
	verbsDir := filepath.Join(tmpDir, "verbs")
	os.MkdirAll(verbsDir, 0755)
	os.WriteFile(filepath.Join(verbsDir, "up.sh"), []byte("echo up"), 0644)
	os.WriteFile(filepath.Join(verbsDir, "down.sh"), []byte("echo down"), 0644)
	os.WriteFile(filepath.Join(verbsDir, "custom.sh"), []byte("echo custom"), 0644)
	os.WriteFile(filepath.Join(verbsDir, "README.md"), []byte("not a verb"), 0644)

	verbs := layerListVerbs(tmpDir)
	if len(verbs) != 3 {
		t.Fatalf("expected 3 verbs, got %d: %v", len(verbs), verbs)
	}
	// Should be sorted
	if verbs[0] != "custom" || verbs[1] != "down" || verbs[2] != "up" {
		t.Fatalf("unexpected verb order: %v", verbs)
	}
}

func TestLayerListVerbs_NoVerbsDir(t *testing.T) {
	tmpDir := t.TempDir()
	verbs := layerListVerbs(tmpDir)
	if len(verbs) != 0 {
		t.Fatalf("expected 0 verbs, got %d", len(verbs))
	}
}

func TestLayerGetLinks(t *testing.T) {
	tmpDir := t.TempDir()
	linksContent := `## AUTOGENERATED
# Comment line
Web UI=http://localhost:3000
API=http://localhost:4000
`
	os.WriteFile(filepath.Join(tmpDir, "links.env"), []byte(linksContent), 0644)

	links := layerGetLinks(tmpDir)
	if len(links) != 2 {
		t.Fatalf("expected 2 links, got %d", len(links))
	}
	if links[0].Label != "Web UI" || links[0].URL != "http://localhost:3000" {
		t.Fatalf("unexpected first link: %+v", links[0])
	}
	if links[1].Label != "API" || links[1].URL != "http://localhost:4000" {
		t.Fatalf("unexpected second link: %+v", links[1])
	}
}

func TestLayerGetLinks_NoFile(t *testing.T) {
	tmpDir := t.TempDir()
	links := layerGetLinks(tmpDir)
	if len(links) != 0 {
		t.Fatalf("expected 0 links, got %d", len(links))
	}
}

func TestExpandEnvWithDefaults(t *testing.T) {
	os.Setenv("TEST_VAR_EXPAND", "myvalue")
	defer os.Unsetenv("TEST_VAR_EXPAND")

	// Simple env var
	result := expandEnvWithDefaults("$TEST_VAR_EXPAND")
	if result != "myvalue" {
		t.Fatalf("expected 'myvalue', got '%s'", result)
	}

	// Env var with default, var is set
	result = expandEnvWithDefaults("${TEST_VAR_EXPAND:-fallback}")
	if result != "myvalue" {
		t.Fatalf("expected 'myvalue', got '%s'", result)
	}

	// Env var with default, var is NOT set
	result = expandEnvWithDefaults("${NONEXISTENT_VAR_XYZ:-fallback}")
	if result != "fallback" {
		t.Fatalf("expected 'fallback', got '%s'", result)
	}

	// Mixed
	result = expandEnvWithDefaults("http://localhost:${NONEXISTENT_PORT:-8080}/api")
	if result != "http://localhost:8080/api" {
		t.Fatalf("expected 'http://localhost:8080/api', got '%s'", result)
	}
}

func TestLoadDotEnv(t *testing.T) {
	tmpDir := t.TempDir()
	envContent := `# comment
KEY1=value1
KEY2=value2

# another comment
KEY3=value with spaces
`
	envFile := filepath.Join(tmpDir, ".env")
	os.WriteFile(envFile, []byte(envContent), 0644)

	err := loadDotEnv(envFile)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if os.Getenv("KEY1") != "value1" {
		t.Fatalf("expected KEY1=value1, got '%s'", os.Getenv("KEY1"))
	}
	if os.Getenv("KEY2") != "value2" {
		t.Fatalf("expected KEY2=value2, got '%s'", os.Getenv("KEY2"))
	}
	if os.Getenv("KEY3") != "value with spaces" {
		t.Fatalf("expected KEY3='value with spaces', got '%s'", os.Getenv("KEY3"))
	}

	// Cleanup
	os.Unsetenv("KEY1")
	os.Unsetenv("KEY2")
	os.Unsetenv("KEY3")
}

func TestLoadDotEnv_NonExistent(t *testing.T) {
	err := loadDotEnv("/nonexistent/path/.env")
	if err != nil {
		t.Fatalf("should not error on nonexistent file, got: %v", err)
	}
}

func TestListStacks(t *testing.T) {
	tmpDir := t.TempDir()
	stacksDir := filepath.Join(tmpDir, "stacks")
	os.MkdirAll(stacksDir, 0755)

	os.WriteFile(filepath.Join(stacksDir, "dev.yaml"), []byte(`version: v0
stack:
  description: "Dev stack"
  layers: []
`), 0644)
	os.WriteFile(filepath.Join(stacksDir, "prod.yaml"), []byte(`version: v0
stack:
  layers: []
`), 0644)

	err := ListStacks(tmpDir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestListLayers(t *testing.T) {
	tmpDir := t.TempDir()
	layersDir := filepath.Join(tmpDir, "layers")

	// Create shell layer
	shellPlan := filepath.Join(layersDir, "1.services", "web")
	os.MkdirAll(filepath.Join(shellPlan, "verbs"), 0755)
	os.WriteFile(filepath.Join(shellPlan, "verbs", "up.sh"), []byte("echo up"), 0644)

	// Create another shell layer
	shellPlan2 := filepath.Join(layersDir, "2.tools", "setup")
	os.MkdirAll(filepath.Join(shellPlan2, "verbs"), 0755)
	os.WriteFile(filepath.Join(shellPlan2, "verbs", "up.sh"), []byte("echo up"), 0644)

	err := ListLayers(tmpDir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestLayerRunHook_NoApplyFile(t *testing.T) {
	tmpDir := t.TempDir()
	// Should not error when k2.apply.yaml doesn't exist
	err := layerRunHook(tmpDir, "pre_start")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestLayerRunHook_NoHook(t *testing.T) {
	tmpDir := t.TempDir()
	applyContent := `k2:
  body:
    hooks: {}
`
	os.WriteFile(filepath.Join(tmpDir, "k2.apply.yaml"), []byte(applyContent), 0644)

	err := layerRunHook(tmpDir, "pre_start")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestLayerRunHook_WithHook(t *testing.T) {
	tmpDir := t.TempDir()
	markerFile := filepath.Join(tmpDir, "hook_ran")
	applyContent := `k2:
  body:
    hooks:
      pre_start: "touch ` + markerFile + `"
`
	os.WriteFile(filepath.Join(tmpDir, "k2.apply.yaml"), []byte(applyContent), 0644)

	err := layerRunHook(tmpDir, "pre_start")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if _, err := os.Stat(markerFile); os.IsNotExist(err) {
		t.Fatal("hook did not run - marker file not created")
	}
}

// --- layerResolvePath ---

func TestLayerResolvePath(t *testing.T) {
	result := layerResolvePath("/project", "layers/1.services", "my-plan")
	expected := filepath.Join("/project", "layers/1.services", "my-plan")
	if result != expected {
		t.Fatalf("expected %s, got %s", expected, result)
	}
}

// --- layerStart ---

func TestLayerStart(t *testing.T) {
	tmpDir := t.TempDir()
	verbsDir := filepath.Join(tmpDir, "verbs")
	os.MkdirAll(verbsDir, 0755)
	marker := filepath.Join(tmpDir, "started")
	os.WriteFile(filepath.Join(verbsDir, "up.sh"), []byte("#!/bin/bash\ntouch "+marker), 0755)

	err := layerStart(tmpDir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if _, err := os.Stat(marker); os.IsNotExist(err) {
		t.Fatal("up.sh did not run")
	}
}

func TestLayerStart_Failure(t *testing.T) {
	tmpDir := t.TempDir()
	verbsDir := filepath.Join(tmpDir, "verbs")
	os.MkdirAll(verbsDir, 0755)
	os.WriteFile(filepath.Join(verbsDir, "up.sh"), []byte("#!/bin/bash\nexit 1"), 0755)

	err := layerStart(tmpDir)
	if err == nil {
		t.Fatal("expected error from failing up.sh")
	}
}

// --- layerStop ---

func TestLayerStop(t *testing.T) {
	tmpDir := t.TempDir()
	verbsDir := filepath.Join(tmpDir, "verbs")
	os.MkdirAll(verbsDir, 0755)
	marker := filepath.Join(tmpDir, "stopped")
	os.WriteFile(filepath.Join(verbsDir, "down.sh"), []byte("#!/bin/bash\ntouch "+marker), 0755)

	err := layerStop(tmpDir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if _, err := os.Stat(marker); os.IsNotExist(err) {
		t.Fatal("down.sh did not run")
	}
}

func TestLayerStop_NoDownScript(t *testing.T) {
	tmpDir := t.TempDir()
	err := layerStop(tmpDir)
	if err != nil {
		t.Fatalf("expected nil when no down.sh, got: %v", err)
	}
}

func TestLayerStop_Failure(t *testing.T) {
	tmpDir := t.TempDir()
	verbsDir := filepath.Join(tmpDir, "verbs")
	os.MkdirAll(verbsDir, 0755)
	os.WriteFile(filepath.Join(verbsDir, "down.sh"), []byte("#!/bin/bash\nexit 1"), 0755)

	err := layerStop(tmpDir)
	if err == nil {
		t.Fatal("expected error from failing down.sh")
	}
}

// --- layerStatus ---

func TestLayerStatus_WithStatusScript(t *testing.T) {
	tmpDir := t.TempDir()
	verbsDir := filepath.Join(tmpDir, "verbs")
	os.MkdirAll(verbsDir, 0755)
	os.WriteFile(filepath.Join(verbsDir, "up.sh"), []byte("echo up"), 0644)
	os.WriteFile(filepath.Join(verbsDir, "status.sh"), []byte("#!/bin/bash\necho running"), 0755)

	status := layerStatus(tmpDir)
	if status != "RUNNING" {
		t.Fatalf("expected RUNNING, got %s", status)
	}
}

func TestLayerStatus_NoStatusScript_Shell(t *testing.T) {
	tmpDir := t.TempDir()
	verbsDir := filepath.Join(tmpDir, "verbs")
	os.MkdirAll(verbsDir, 0755)
	os.WriteFile(filepath.Join(verbsDir, "up.sh"), []byte("echo up"), 0644)

	status := layerStatus(tmpDir)
	if status != "PRESENT" {
		t.Fatalf("expected PRESENT, got %s", status)
	}
}

func TestLayerStatus_NoStatusScript_Unknown(t *testing.T) {
	tmpDir := t.TempDir()
	status := layerStatus(tmpDir)
	if status != "UNKNOWN" {
		t.Fatalf("expected UNKNOWN, got %s", status)
	}
}

func TestLayerStatus_StatusScriptFails(t *testing.T) {
	tmpDir := t.TempDir()
	verbsDir := filepath.Join(tmpDir, "verbs")
	os.MkdirAll(verbsDir, 0755)
	os.WriteFile(filepath.Join(verbsDir, "status.sh"), []byte("#!/bin/bash\nexit 1"), 0755)

	status := layerStatus(tmpDir)
	if status != "DOWN" {
		t.Fatalf("expected DOWN, got %s", status)
	}
}

func TestLayerStatus_EmptyOutput(t *testing.T) {
	tmpDir := t.TempDir()
	verbsDir := filepath.Join(tmpDir, "verbs")
	os.MkdirAll(verbsDir, 0755)
	os.WriteFile(filepath.Join(verbsDir, "status.sh"), []byte("#!/bin/bash\necho ''"), 0755)

	status := layerStatus(tmpDir)
	if status != "UNKNOWN" {
		t.Fatalf("expected UNKNOWN, got %s", status)
	}
}

// --- layerHealthcheck ---

func TestLayerHealthcheck_OK(t *testing.T) {
	tmpDir := t.TempDir()
	applyContent := `k2:
  body:
    hooks:
      healthcheck: "true"
`
	os.WriteFile(filepath.Join(tmpDir, "k2.apply.yaml"), []byte(applyContent), 0644)

	result := layerHealthcheck(tmpDir)
	if result != "OK" {
		t.Fatalf("expected OK, got %s", result)
	}
}

func TestLayerHealthcheck_Fail(t *testing.T) {
	tmpDir := t.TempDir()
	applyContent := `k2:
  body:
    hooks:
      healthcheck: "false"
`
	os.WriteFile(filepath.Join(tmpDir, "k2.apply.yaml"), []byte(applyContent), 0644)

	result := layerHealthcheck(tmpDir)
	if result != "FAIL" {
		t.Fatalf("expected FAIL, got %s", result)
	}
}

func TestLayerHealthcheck_NoHook(t *testing.T) {
	tmpDir := t.TempDir()
	result := layerHealthcheck(tmpDir)
	if result != "OK" {
		t.Fatalf("expected OK (no hook = pass), got %s", result)
	}
}

// --- layerGetURL ---

func TestLayerGetURL_WithLinks(t *testing.T) {
	tmpDir := t.TempDir()
	os.WriteFile(filepath.Join(tmpDir, "links.env"), []byte("Web=http://localhost:3000\nAPI=http://localhost:4000\n"), 0644)

	url := layerGetURL(tmpDir)
	if url != "http://localhost:3000" {
		t.Fatalf("expected first URL, got %s", url)
	}
}

func TestLayerGetURL_NoLinks(t *testing.T) {
	tmpDir := t.TempDir()
	url := layerGetURL(tmpDir)
	if url != "" {
		t.Fatalf("expected empty, got %s", url)
	}
}

// --- layerLogs ---

func TestLayerLogs(t *testing.T) {
	tmpDir := t.TempDir()
	verbsDir := filepath.Join(tmpDir, "verbs")
	os.MkdirAll(verbsDir, 0755)
	os.WriteFile(filepath.Join(verbsDir, "logs.sh"), []byte("#!/bin/bash\necho log-output"), 0755)

	err := layerLogs(tmpDir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestLayerLogs_NoScript(t *testing.T) {
	tmpDir := t.TempDir()
	err := layerLogs(tmpDir)
	if err == nil {
		t.Fatal("expected error when no logs.sh")
	}
	if !strings.Contains(err.Error(), "no logs verb") {
		t.Fatalf("unexpected error: %v", err)
	}
}

// --- layerRunVerb ---

func TestLayerRunVerb(t *testing.T) {
	tmpDir := t.TempDir()
	verbsDir := filepath.Join(tmpDir, "verbs")
	os.MkdirAll(verbsDir, 0755)
	marker := filepath.Join(tmpDir, "verb_ran")
	os.WriteFile(filepath.Join(verbsDir, "custom.sh"), []byte("#!/bin/bash\ntouch "+marker), 0755)

	err := layerRunVerb(tmpDir, "custom", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if _, err := os.Stat(marker); os.IsNotExist(err) {
		t.Fatal("verb did not run")
	}
}

func TestLayerRunVerb_WithArgs(t *testing.T) {
	tmpDir := t.TempDir()
	verbsDir := filepath.Join(tmpDir, "verbs")
	os.MkdirAll(verbsDir, 0755)
	outFile := filepath.Join(tmpDir, "args_out")
	os.WriteFile(filepath.Join(verbsDir, "test.sh"), []byte("#!/bin/bash\necho \"$@\" > "+outFile), 0755)

	err := layerRunVerb(tmpDir, "test", []string{"arg1", "arg2"})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	data, _ := os.ReadFile(outFile)
	if strings.TrimSpace(string(data)) != "arg1 arg2" {
		t.Fatalf("expected 'arg1 arg2', got '%s'", strings.TrimSpace(string(data)))
	}
}

func TestLayerRunVerb_NotFound_WithVerbs(t *testing.T) {
	tmpDir := t.TempDir()
	verbsDir := filepath.Join(tmpDir, "verbs")
	os.MkdirAll(verbsDir, 0755)
	os.WriteFile(filepath.Join(verbsDir, "up.sh"), []byte("echo up"), 0644)

	err := layerRunVerb(tmpDir, "nonexistent", nil)
	if err == nil {
		t.Fatal("expected error")
	}
	if !strings.Contains(err.Error(), "not found") || !strings.Contains(err.Error(), "Available: up") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestLayerRunVerb_NotFound_NoVerbs(t *testing.T) {
	tmpDir := t.TempDir()
	err := layerRunVerb(tmpDir, "nonexistent", nil)
	if err == nil {
		t.Fatal("expected error")
	}
	if !strings.Contains(err.Error(), "no verbs available") {
		t.Fatalf("unexpected error: %v", err)
	}
}

// --- exportEnvMap ---

func TestExportEnvMap(t *testing.T) {
	exportEnvMap(map[string]string{
		"TEST_EXPORT_A": "val_a",
		"TEST_EXPORT_B": "val_b",
	})
	defer os.Unsetenv("TEST_EXPORT_A")
	defer os.Unsetenv("TEST_EXPORT_B")

	if os.Getenv("TEST_EXPORT_A") != "val_a" {
		t.Fatalf("expected val_a, got %s", os.Getenv("TEST_EXPORT_A"))
	}
	if os.Getenv("TEST_EXPORT_B") != "val_b" {
		t.Fatalf("expected val_b, got %s", os.Getenv("TEST_EXPORT_B"))
	}
}

// --- loadDefaultsEnv ---

func TestLoadDefaultsEnv(t *testing.T) {
	tmpDir := t.TempDir()
	os.WriteFile(filepath.Join(tmpDir, "defaults.env"), []byte("DEFAULT_KEY=default_val\n"), 0644)

	loadDefaultsEnv(tmpDir)
	defer os.Unsetenv("DEFAULT_KEY")

	if os.Getenv("DEFAULT_KEY") != "default_val" {
		t.Fatalf("expected default_val, got %s", os.Getenv("DEFAULT_KEY"))
	}
}

func TestLoadDefaultsEnv_NoFile(t *testing.T) {
	tmpDir := t.TempDir()
	// Should not panic
	loadDefaultsEnv(tmpDir)
}

// --- StackStore.loadEnv ---

func TestStackStore_LoadEnv(t *testing.T) {
	tmpDir := t.TempDir()
	stacksDir := filepath.Join(tmpDir, "stacks")
	os.MkdirAll(stacksDir, 0755)

	os.WriteFile(filepath.Join(tmpDir, ".env"), []byte("ROOT_VAR=root_val\n"), 0644)
	os.WriteFile(filepath.Join(stacksDir, "test.yaml"), []byte(`version: v0
stack:
  env:
    STACK_VAR: stack_val
  layers: []
`), 0644)

	store, _ := NewStackStore(tmpDir, "test", false)
	store.loadEnv()
	defer os.Unsetenv("ROOT_VAR")
	defer os.Unsetenv("STACK_VAR")

	if os.Getenv("ROOT_VAR") != "root_val" {
		t.Fatalf("expected root_val, got %s", os.Getenv("ROOT_VAR"))
	}
	if os.Getenv("STACK_VAR") != "stack_val" {
		t.Fatalf("expected stack_val, got %s", os.Getenv("STACK_VAR"))
	}
}

// --- StackStore.exportLayerEnv ---

func TestStackStore_ExportLayerEnv(t *testing.T) {
	tmpDir := t.TempDir()
	stacksDir := filepath.Join(tmpDir, "stacks")
	os.MkdirAll(stacksDir, 0755)

	planDir := filepath.Join(tmpDir, "layers", "1.svc", "myplan")
	os.MkdirAll(planDir, 0755)
	os.WriteFile(filepath.Join(planDir, "defaults.env"), []byte("DEF_VAR=def_val\n"), 0644)

	os.WriteFile(filepath.Join(stacksDir, "test.yaml"), []byte(`version: v0
stack:
  layers:
    - layer: layers/1.svc
      plan: myplan
      env:
        LAYER_VAR: layer_val
`), 0644)

	store, _ := NewStackStore(tmpDir, "test", false)
	store.exportLayerEnv(0)
	defer os.Unsetenv("LAYER_VAR")
	defer os.Unsetenv("DEF_VAR")

	if os.Getenv("LAYER_VAR") != "layer_val" {
		t.Fatalf("expected layer_val, got %s", os.Getenv("LAYER_VAR"))
	}
	if os.Getenv("DEF_VAR") != "def_val" {
		t.Fatalf("expected def_val, got %s", os.Getenv("DEF_VAR"))
	}
}

// --- StackStore.Up ---

func createTestStack(t *testing.T) (string, *StackStore) {
	t.Helper()
	tmpDir := t.TempDir()
	stacksDir := filepath.Join(tmpDir, "stacks")
	os.MkdirAll(stacksDir, 0755)

	// Create layer with verbs
	planDir := filepath.Join(tmpDir, "layers", "1.svc", "app")
	verbsDir := filepath.Join(planDir, "verbs")
	os.MkdirAll(verbsDir, 0755)
	os.WriteFile(filepath.Join(verbsDir, "up.sh"), []byte("#!/bin/bash\ntouch "+filepath.Join(planDir, "up_marker")), 0755)
	os.WriteFile(filepath.Join(verbsDir, "down.sh"), []byte("#!/bin/bash\ntouch "+filepath.Join(planDir, "down_marker")), 0755)
	os.WriteFile(filepath.Join(verbsDir, "status.sh"), []byte("#!/bin/bash\necho UP"), 0755)
	os.WriteFile(filepath.Join(verbsDir, "logs.sh"), []byte("#!/bin/bash\necho app-logs"), 0755)
	os.WriteFile(filepath.Join(planDir, "links.env"), []byte("App=http://localhost:8080\n"), 0644)

	os.WriteFile(filepath.Join(stacksDir, "test.yaml"), []byte(`version: v0
stack:
  description: "Test"
  layers:
    - layer: layers/1.svc
      plan: app
`), 0644)

	store, err := NewStackStore(tmpDir, "test", false)
	if err != nil {
		t.Fatalf("setup failed: %v", err)
	}
	return tmpDir, store
}

func TestStackStore_Up(t *testing.T) {
	tmpDir, store := createTestStack(t)

	err := store.Up()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	marker := filepath.Join(tmpDir, "layers", "1.svc", "app", "up_marker")
	if _, err := os.Stat(marker); os.IsNotExist(err) {
		t.Fatal("up.sh did not run during Up()")
	}
}

func TestStackStore_Down(t *testing.T) {
	tmpDir, store := createTestStack(t)

	err := store.Down()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	marker := filepath.Join(tmpDir, "layers", "1.svc", "app", "down_marker")
	if _, err := os.Stat(marker); os.IsNotExist(err) {
		t.Fatal("down.sh did not run during Down()")
	}
}

func TestStackStore_Restart(t *testing.T) {
	tmpDir, store := createTestStack(t)

	err := store.Restart()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	upMarker := filepath.Join(tmpDir, "layers", "1.svc", "app", "up_marker")
	downMarker := filepath.Join(tmpDir, "layers", "1.svc", "app", "down_marker")
	if _, err := os.Stat(upMarker); os.IsNotExist(err) {
		t.Fatal("up.sh did not run during Restart()")
	}
	if _, err := os.Stat(downMarker); os.IsNotExist(err) {
		t.Fatal("down.sh did not run during Restart()")
	}
}

func TestStackStore_Status(t *testing.T) {
	_, store := createTestStack(t)

	err := store.Status()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestStackStore_Healthcheck(t *testing.T) {
	_, store := createTestStack(t)

	err := store.Healthcheck()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestStackStore_Urls(t *testing.T) {
	_, store := createTestStack(t)

	err := store.Urls()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestStackStore_Urls_NoLinks(t *testing.T) {
	tmpDir := t.TempDir()
	stacksDir := filepath.Join(tmpDir, "stacks")
	os.MkdirAll(stacksDir, 0755)

	planDir := filepath.Join(tmpDir, "layers", "1.svc", "app", "verbs")
	os.MkdirAll(planDir, 0755)
	os.WriteFile(filepath.Join(planDir, "up.sh"), []byte("echo up"), 0644)

	os.WriteFile(filepath.Join(stacksDir, "test.yaml"), []byte(`version: v0
stack:
  layers:
    - layer: layers/1.svc
      plan: app
`), 0644)

	store, _ := NewStackStore(tmpDir, "test", false)
	err := store.Urls()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

// --- StackStore.Run ---

func TestStackStore_Run_ListVerbs(t *testing.T) {
	_, store := createTestStack(t)

	err := store.Run("app", "", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestStackStore_Run_ExecuteVerb(t *testing.T) {
	tmpDir, store := createTestStack(t)
	marker := filepath.Join(tmpDir, "layers", "1.svc", "app", "custom_ran")

	verbsDir := filepath.Join(tmpDir, "layers", "1.svc", "app", "verbs")
	os.WriteFile(filepath.Join(verbsDir, "custom.sh"), []byte("#!/bin/bash\ntouch "+marker), 0755)

	err := store.Run("app", "custom", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if _, err := os.Stat(marker); os.IsNotExist(err) {
		t.Fatal("custom verb did not run")
	}
}

func TestStackStore_Run_LayerNotFound(t *testing.T) {
	_, store := createTestStack(t)

	err := store.Run("nonexistent", "up", nil)
	if err == nil {
		t.Fatal("expected error for nonexistent layer")
	}
	if !strings.Contains(err.Error(), "not found") {
		t.Fatalf("unexpected error: %v", err)
	}
}

// --- StackStore.Logs ---

func TestStackStore_Logs_TargetLayer(t *testing.T) {
	_, store := createTestStack(t)

	err := store.Logs("app")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestStackStore_Logs_TargetNotFound(t *testing.T) {
	_, store := createTestStack(t)

	err := store.Logs("nonexistent")
	if err == nil {
		t.Fatal("expected error")
	}
	if !strings.Contains(err.Error(), "not found") {
		t.Fatalf("unexpected error: %v", err)
	}
}

// --- Up/Down with missing layer dir ---

func TestStackStore_Up_MissingLayerDir(t *testing.T) {
	tmpDir := t.TempDir()
	stacksDir := filepath.Join(tmpDir, "stacks")
	os.MkdirAll(stacksDir, 0755)

	os.WriteFile(filepath.Join(stacksDir, "test.yaml"), []byte(`version: v0
stack:
  layers:
    - layer: layers/missing
      plan: gone
`), 0644)

	store, _ := NewStackStore(tmpDir, "test", false)
	err := store.Up()
	if err != nil {
		t.Fatalf("Up should not error for missing layers (just skip): %v", err)
	}
}

func TestStackStore_Down_UnknownRecipe(t *testing.T) {
	tmpDir := t.TempDir()
	stacksDir := filepath.Join(tmpDir, "stacks")
	os.MkdirAll(stacksDir, 0755)

	planDir := filepath.Join(tmpDir, "layers", "1.svc", "app")
	os.MkdirAll(planDir, 0755)
	// No verbs = unknown

	os.WriteFile(filepath.Join(stacksDir, "test.yaml"), []byte(`version: v0
stack:
  layers:
    - layer: layers/1.svc
      plan: app
`), 0644)

	store, _ := NewStackStore(tmpDir, "test", false)
	err := store.Down()
	if err != nil {
		t.Fatalf("Down should not error for unknown recipe (just skip): %v", err)
	}
}

// --- logDebug ---

func TestStackStore_LogDebug(t *testing.T) {
	tmpDir := t.TempDir()
	stacksDir := filepath.Join(tmpDir, "stacks")
	os.MkdirAll(stacksDir, 0755)
	os.WriteFile(filepath.Join(stacksDir, "test.yaml"), []byte(`version: v0
stack:
  layers: []
`), 0644)

	store, _ := NewStackStore(tmpDir, "test", true)
	// Should not panic
	store.logDebug("test %s", "message")

	store2, _ := NewStackStore(tmpDir, "test", false)
	// Should not panic (noop)
	store2.logDebug("test %s", "message")
}

// --- layerHasVerb ---

func TestLayerHasVerb_Present(t *testing.T) {
	tmpDir := t.TempDir()
	verbsDir := filepath.Join(tmpDir, "verbs")
	os.MkdirAll(verbsDir, 0755)
	os.WriteFile(filepath.Join(verbsDir, "build.sh"), []byte("echo build"), 0644)

	if !layerHasVerb(tmpDir, "build") {
		t.Fatal("expected layerHasVerb to return true")
	}
}

func TestLayerHasVerb_Missing(t *testing.T) {
	tmpDir := t.TempDir()
	if layerHasVerb(tmpDir, "build") {
		t.Fatal("expected layerHasVerb to return false when no verb")
	}
}

func TestLayerHasVerb_OtherVerbPresent(t *testing.T) {
	tmpDir := t.TempDir()
	verbsDir := filepath.Join(tmpDir, "verbs")
	os.MkdirAll(verbsDir, 0755)
	os.WriteFile(filepath.Join(verbsDir, "up.sh"), []byte("echo up"), 0644)

	if layerHasVerb(tmpDir, "build") {
		t.Fatal("expected layerHasVerb to return false for absent verb")
	}
	if !layerHasVerb(tmpDir, "up") {
		t.Fatal("expected layerHasVerb to return true for present verb")
	}
}

// --- StackStore.Rm ---

func TestStackStore_Rm_RunsWhenVerbPresent(t *testing.T) {
	tmpDir, store := createTestStack(t)

	verbsDir := filepath.Join(tmpDir, "layers", "1.svc", "app", "verbs")
	marker := filepath.Join(tmpDir, "layers", "1.svc", "app", "rm_marker")
	os.WriteFile(filepath.Join(verbsDir, "rm.sh"), []byte("#!/bin/bash\ntouch "+marker), 0755)

	err := store.Rm()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if _, err := os.Stat(marker); os.IsNotExist(err) {
		t.Fatal("rm.sh did not run during Rm()")
	}
}

func TestStackStore_Rm_SkipsWhenNoVerb(t *testing.T) {
	_, store := createTestStack(t)
	// createTestStack has no rm.sh — should succeed silently
	err := store.Rm()
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

// --- StackStore.Build ---

func TestStackStore_Build_AllLayers(t *testing.T) {
	tmpDir, store := createTestStack(t)

	// Add build.sh to the layer
	verbsDir := filepath.Join(tmpDir, "layers", "1.svc", "app", "verbs")
	marker := filepath.Join(tmpDir, "layers", "1.svc", "app", "build_marker")
	os.WriteFile(filepath.Join(verbsDir, "build.sh"), []byte("#!/bin/bash\ntouch "+marker), 0755)

	err := store.Build("")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if _, err := os.Stat(marker); os.IsNotExist(err) {
		t.Fatal("build.sh did not run during Build()")
	}
}

func TestStackStore_Build_TargetLayer(t *testing.T) {
	tmpDir, store := createTestStack(t)

	verbsDir := filepath.Join(tmpDir, "layers", "1.svc", "app", "verbs")
	marker := filepath.Join(tmpDir, "layers", "1.svc", "app", "build_marker")
	os.WriteFile(filepath.Join(verbsDir, "build.sh"), []byte("#!/bin/bash\ntouch "+marker), 0755)

	err := store.Build("app")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if _, err := os.Stat(marker); os.IsNotExist(err) {
		t.Fatal("build.sh did not run for target layer")
	}
}

func TestStackStore_Build_TargetNotFound(t *testing.T) {
	_, store := createTestStack(t)

	err := store.Build("nonexistent")
	if err == nil {
		t.Fatal("expected error for nonexistent layer")
	}
	if !strings.Contains(err.Error(), "not found") {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestStackStore_Build_NoBuildScript(t *testing.T) {
	_, store := createTestStack(t)

	// No build.sh in the layer — should skip gracefully
	err := store.Build("")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestStackStore_Build_MissingLayerDir(t *testing.T) {
	tmpDir := t.TempDir()
	stacksDir := filepath.Join(tmpDir, "stacks")
	os.MkdirAll(stacksDir, 0755)

	os.WriteFile(filepath.Join(stacksDir, "test.yaml"), []byte(`version: v0
stack:
  layers:
    - layer: layers/missing
      plan: app
`), 0644)

	store, _ := NewStackStore(tmpDir, "test", false)
	err := store.Build("")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

// --- logShellCmd ---

func TestLogShellCmd(t *testing.T) {
	tmpDir := t.TempDir()
	cmd := logShellCmd(tmpDir)
	if cmd.Dir != tmpDir {
		t.Fatalf("expected Dir=%s, got %s", tmpDir, cmd.Dir)
	}
	if cmd.Args[0] != "bash" || cmd.Args[1] != "verbs/logs.sh" {
		t.Fatalf("unexpected args: %v", cmd.Args)
	}
}

// --- StackStore.Exec ---

func TestStackStore_Exec_RunsOnAllLayers(t *testing.T) {
	tmpDir, store := createTestStack(t)

	verbsDir := filepath.Join(tmpDir, "layers", "1.svc", "app", "verbs")
	marker := filepath.Join(tmpDir, "layers", "1.svc", "app", "deploy_marker")
	os.WriteFile(filepath.Join(verbsDir, "deploy.sh"), []byte("#!/bin/bash\ntouch "+marker), 0755)

	err := store.Exec("deploy", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if _, err := os.Stat(marker); os.IsNotExist(err) {
		t.Fatal("deploy.sh did not run during Exec()")
	}
}

func TestStackStore_Exec_WithArgs(t *testing.T) {
	tmpDir, store := createTestStack(t)

	verbsDir := filepath.Join(tmpDir, "layers", "1.svc", "app", "verbs")
	outFile := filepath.Join(tmpDir, "layers", "1.svc", "app", "args_out")
	os.WriteFile(filepath.Join(verbsDir, "greet.sh"), []byte("#!/bin/bash\necho \"$@\" > "+outFile), 0755)

	err := store.Exec("greet", []string{"hello", "world"})
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	data, _ := os.ReadFile(outFile)
	if strings.TrimSpace(string(data)) != "hello world" {
		t.Fatalf("expected 'hello world', got '%s'", strings.TrimSpace(string(data)))
	}
}

func TestStackStore_Exec_SkipsLayersWithoutVerb(t *testing.T) {
	_, store := createTestStack(t)

	// No "deploy.sh" in any layer — should succeed with 0 executed
	err := store.Exec("deploy", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestStackStore_Exec_VerbFails(t *testing.T) {
	tmpDir, store := createTestStack(t)

	verbsDir := filepath.Join(tmpDir, "layers", "1.svc", "app", "verbs")
	os.WriteFile(filepath.Join(verbsDir, "fail.sh"), []byte("#!/bin/bash\nexit 1"), 0755)

	err := store.Exec("fail", nil)
	if err != nil {
		t.Fatalf("unexpected error from Exec (failures are reported, not returned): %v", err)
	}
}

func TestStackStore_Exec_MultipleLayersSelective(t *testing.T) {
	tmpDir := t.TempDir()
	stacksDir := filepath.Join(tmpDir, "stacks")
	os.MkdirAll(stacksDir, 0755)

	// Layer A has migrate.sh, Layer B does not
	layerA := filepath.Join(tmpDir, "layers", "1.svc", "app-a")
	layerB := filepath.Join(tmpDir, "layers", "1.svc", "app-b")
	os.MkdirAll(filepath.Join(layerA, "verbs"), 0755)
	os.MkdirAll(filepath.Join(layerB, "verbs"), 0755)

	markerA := filepath.Join(layerA, "migrated")
	os.WriteFile(filepath.Join(layerA, "verbs", "up.sh"), []byte("echo up"), 0644)
	os.WriteFile(filepath.Join(layerA, "verbs", "migrate.sh"), []byte("#!/bin/bash\ntouch "+markerA), 0755)
	os.WriteFile(filepath.Join(layerB, "verbs", "up.sh"), []byte("echo up"), 0644)
	// app-b intentionally has no migrate.sh

	os.WriteFile(filepath.Join(stacksDir, "test.yaml"), []byte(`version: v0
stack:
  layers:
    - layer: layers/1.svc
      plan: app-a
    - layer: layers/1.svc
      plan: app-b
`), 0644)

	store, _ := NewStackStore(tmpDir, "test", false)
	err := store.Exec("migrate", nil)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if _, err := os.Stat(markerA); os.IsNotExist(err) {
		t.Fatal("migrate.sh did not run on app-a")
	}
	// app-b had no migrate.sh — no marker expected, no error expected
}
