package stores

import (
	"os"
	"path/filepath"
	"testing"
)

func TestNewStackStore(t *testing.T) {
	tmpDir := t.TempDir()

	// Create stacks directory and a stack file
	stacksDir := filepath.Join(tmpDir, "stacks")
	os.MkdirAll(stacksDir, 0755)

	stackContent := `version: v0
stack:
  description: "Test stack"
  env:
    TZ: Europe/Paris
    TEST_NETWORK: testnet
  layers:
    - layer: layers/1.services
      plan: my-service
      env:
        PORT: "8080"
    - layer: layers/2.proxy
      plan: my-proxy
`
	os.WriteFile(filepath.Join(stacksDir, "test.yaml"), []byte(stackContent), 0644)

	store, err := NewStackStore(tmpDir, "test", false)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if store.Name != "test" {
		t.Fatalf("expected name 'test', got '%s'", store.Name)
	}
	if store.Definition.Stack.Description != "Test stack" {
		t.Fatalf("expected description 'Test stack', got '%s'", store.Definition.Stack.Description)
	}
	if len(store.Definition.Stack.Layers) != 2 {
		t.Fatalf("expected 2 layers, got %d", len(store.Definition.Stack.Layers))
	}
	if store.Definition.Stack.Layers[0].Plan != "my-service" {
		t.Fatalf("expected plan 'my-service', got '%s'", store.Definition.Stack.Layers[0].Plan)
	}
	if store.Definition.Stack.Layers[0].Env["PORT"] != "8080" {
		t.Fatalf("expected PORT=8080, got '%s'", store.Definition.Stack.Layers[0].Env["PORT"])
	}
}

func TestNewStackStore_NotFound(t *testing.T) {
	tmpDir := t.TempDir()
	os.MkdirAll(filepath.Join(tmpDir, "stacks"), 0755)

	_, err := NewStackStore(tmpDir, "nonexistent", false)
	if err == nil {
		t.Fatal("expected error for nonexistent stack")
	}
}

func TestLayerDetectType_Shell(t *testing.T) {
	tmpDir := t.TempDir()
	verbsDir := filepath.Join(tmpDir, "verbs")
	os.MkdirAll(verbsDir, 0755)
	os.WriteFile(filepath.Join(verbsDir, "up.sh"), []byte("echo up"), 0644)

	rt := layerDetectType(tmpDir)
	if rt != recipeShell {
		t.Fatalf("expected shell, got %s", rt)
	}
}

func TestLayerDetectType_Unknown(t *testing.T) {
	tmpDir := t.TempDir()
	rt := layerDetectType(tmpDir)
	if rt != recipeUnknown {
		t.Fatalf("expected unknown, got %s", rt)
	}
}

func TestLayerRef(t *testing.T) {
	ref := layerRef("layers/2.locals-subscriptions", "ollama-registry")
	if ref != "2.locals-subscriptions/ollama-registry" {
		t.Fatalf("unexpected ref: %s", ref)
	}
}

func TestLayerListVerbs(t *testing.T) {
	tmpDir := t.TempDir()
	verbsDir := filepath.Join(tmpDir, "verbs")
	os.MkdirAll(verbsDir, 0755)
	os.WriteFile(filepath.Join(verbsDir, "up.sh"), []byte("echo up"), 0644)
	os.WriteFile(filepath.Join(verbsDir, "down.sh"), []byte("echo down"), 0644)
	os.WriteFile(filepath.Join(verbsDir, "custom.sh"), []byte("echo custom"), 0644)
	os.WriteFile(filepath.Join(verbsDir, "README.md"), []byte("not a verb"), 0644)

	verbs := layerListVerbs(tmpDir)
	if len(verbs) != 3 {
		t.Fatalf("expected 3 verbs, got %d: %v", len(verbs), verbs)
	}
	// Should be sorted
	if verbs[0] != "custom" || verbs[1] != "down" || verbs[2] != "up" {
		t.Fatalf("unexpected verb order: %v", verbs)
	}
}

func TestLayerListVerbs_NoVerbsDir(t *testing.T) {
	tmpDir := t.TempDir()
	verbs := layerListVerbs(tmpDir)
	if len(verbs) != 0 {
		t.Fatalf("expected 0 verbs, got %d", len(verbs))
	}
}

func TestLayerGetLinks(t *testing.T) {
	tmpDir := t.TempDir()
	linksContent := `## AUTOGENERATED
# Comment line
Web UI=http://localhost:3000
API=http://localhost:4000
`
	os.WriteFile(filepath.Join(tmpDir, "links.env"), []byte(linksContent), 0644)

	links := layerGetLinks(tmpDir)
	if len(links) != 2 {
		t.Fatalf("expected 2 links, got %d", len(links))
	}
	if links[0].Label != "Web UI" || links[0].URL != "http://localhost:3000" {
		t.Fatalf("unexpected first link: %+v", links[0])
	}
	if links[1].Label != "API" || links[1].URL != "http://localhost:4000" {
		t.Fatalf("unexpected second link: %+v", links[1])
	}
}

func TestLayerGetLinks_NoFile(t *testing.T) {
	tmpDir := t.TempDir()
	links := layerGetLinks(tmpDir)
	if len(links) != 0 {
		t.Fatalf("expected 0 links, got %d", len(links))
	}
}

func TestExpandEnvWithDefaults(t *testing.T) {
	os.Setenv("TEST_VAR_EXPAND", "myvalue")
	defer os.Unsetenv("TEST_VAR_EXPAND")

	// Simple env var
	result := expandEnvWithDefaults("$TEST_VAR_EXPAND")
	if result != "myvalue" {
		t.Fatalf("expected 'myvalue', got '%s'", result)
	}

	// Env var with default, var is set
	result = expandEnvWithDefaults("${TEST_VAR_EXPAND:-fallback}")
	if result != "myvalue" {
		t.Fatalf("expected 'myvalue', got '%s'", result)
	}

	// Env var with default, var is NOT set
	result = expandEnvWithDefaults("${NONEXISTENT_VAR_XYZ:-fallback}")
	if result != "fallback" {
		t.Fatalf("expected 'fallback', got '%s'", result)
	}

	// Mixed
	result = expandEnvWithDefaults("http://localhost:${NONEXISTENT_PORT:-8080}/api")
	if result != "http://localhost:8080/api" {
		t.Fatalf("expected 'http://localhost:8080/api', got '%s'", result)
	}
}

func TestLoadDotEnv(t *testing.T) {
	tmpDir := t.TempDir()
	envContent := `# comment
KEY1=value1
KEY2=value2

# another comment
KEY3=value with spaces
`
	envFile := filepath.Join(tmpDir, ".env")
	os.WriteFile(envFile, []byte(envContent), 0644)

	err := loadDotEnv(envFile)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if os.Getenv("KEY1") != "value1" {
		t.Fatalf("expected KEY1=value1, got '%s'", os.Getenv("KEY1"))
	}
	if os.Getenv("KEY2") != "value2" {
		t.Fatalf("expected KEY2=value2, got '%s'", os.Getenv("KEY2"))
	}
	if os.Getenv("KEY3") != "value with spaces" {
		t.Fatalf("expected KEY3='value with spaces', got '%s'", os.Getenv("KEY3"))
	}

	// Cleanup
	os.Unsetenv("KEY1")
	os.Unsetenv("KEY2")
	os.Unsetenv("KEY3")
}

func TestLoadDotEnv_NonExistent(t *testing.T) {
	err := loadDotEnv("/nonexistent/path/.env")
	if err != nil {
		t.Fatalf("should not error on nonexistent file, got: %v", err)
	}
}

func TestListStacks(t *testing.T) {
	tmpDir := t.TempDir()
	stacksDir := filepath.Join(tmpDir, "stacks")
	os.MkdirAll(stacksDir, 0755)

	os.WriteFile(filepath.Join(stacksDir, "dev.yaml"), []byte(`version: v0
stack:
  description: "Dev stack"
  layers: []
`), 0644)
	os.WriteFile(filepath.Join(stacksDir, "prod.yaml"), []byte(`version: v0
stack:
  layers: []
`), 0644)

	err := ListStacks(tmpDir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestListLayers(t *testing.T) {
	tmpDir := t.TempDir()
	layersDir := filepath.Join(tmpDir, "layers")

	// Create shell layer
	shellPlan := filepath.Join(layersDir, "1.services", "web")
	os.MkdirAll(filepath.Join(shellPlan, "verbs"), 0755)
	os.WriteFile(filepath.Join(shellPlan, "verbs", "up.sh"), []byte("echo up"), 0644)

	// Create another shell layer
	shellPlan2 := filepath.Join(layersDir, "2.tools", "setup")
	os.MkdirAll(filepath.Join(shellPlan2, "verbs"), 0755)
	os.WriteFile(filepath.Join(shellPlan2, "verbs", "up.sh"), []byte("echo up"), 0644)

	err := ListLayers(tmpDir)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestLayerRunHook_NoApplyFile(t *testing.T) {
	tmpDir := t.TempDir()
	// Should not error when k2.apply.yaml doesn't exist
	err := layerRunHook(tmpDir, "pre_start")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestLayerRunHook_NoHook(t *testing.T) {
	tmpDir := t.TempDir()
	applyContent := `k2:
  body:
    hooks: {}
`
	os.WriteFile(filepath.Join(tmpDir, "k2.apply.yaml"), []byte(applyContent), 0644)

	err := layerRunHook(tmpDir, "pre_start")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
}

func TestLayerRunHook_WithHook(t *testing.T) {
	tmpDir := t.TempDir()
	markerFile := filepath.Join(tmpDir, "hook_ran")
	applyContent := `k2:
  body:
    hooks:
      pre_start: "touch ` + markerFile + `"
`
	os.WriteFile(filepath.Join(tmpDir, "k2.apply.yaml"), []byte(applyContent), 0644)

	err := layerRunHook(tmpDir, "pre_start")
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	if _, err := os.Stat(markerFile); os.IsNotExist(err) {
		t.Fatal("hook did not run - marker file not created")
	}
}
