name : "Code coverage"
on:
    pull_request:
      types: [opened, reopened, synchronize]
    push:
      branches:
        - "main"  
jobs:
    unit_tests:
      name: "code coverage"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
  
        - name: Setup Go 1.24.x
          uses: actions/setup-go@v5
          with:
            go-version: 1.24.x
  
        - name: Test
          run: make test
  
        - name: Archive code coverage results
          uses: actions/upload-artifact@v4
          with:
            name: code-coverage
            path: profile.coverage # Make sure to use the same file name you chose for the "-coverprofile" in the "Test" step
  
    code_coverage:
      name: "Code coverage report"
      if: github.event_name == 'pull_request' # Do not run when workflow is triggered by push to main branch
      runs-on: ubuntu-latest
      needs: unit_tests # Depends on the artifact uploaded by the "unit_tests" job
      permissions:
        contents: read
        actions: read # to download code coverage results from "test" job
        pull-requests: write # write permission needed to comment on PR
      steps:
        - uses: fgrosse/go-coverage-report@v1.0.2 # Consider using a Git revision for maximum security
          with:
            coverage-artifact-name: "code-coverage" # can be omitted if you used this default value
            coverage-file-name: "profile.coverage" # can be omitted if you used this default value